In [1]:
import numpy as np


In [3]:
## create a 1 dimensional array
my1dArray = np.array([1,2,3])
print(my1dArray)

[1 2 3]


In [7]:
## create a 2 dimensional array
my2dArray = np.array([[1,2,3], [4,5,6]])
print(my2dArray)


[[1 2 3]
 [4 5 6]]


In [9]:
##create an array specifying the datatype
my2dArrayFloat = np.array([[1,2,3], [4,5,6]], dtype = 'float')
print(my2dArrayFloat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
my2dArrayFloat.dtype

dtype('float64')

In [11]:
## creating a 2d array with data type in another form
my2dArrayFloat32 = np.array([[1,2,3], [4,5,6]],dtype=np.float16)
print(my2dArrayFloat32)

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
my2dArrayFloat32.dtype

dtype('float16')

In [13]:
## confirming a data type
my2dArrayFloat.dtype

dtype('float64')

In [16]:
## create an array
## indicate a datatype to the array
## print the array and print the datatype

my1dArray = np.array([5,6,7], dtype = int)
print(my1dArray)




[5 6 7]


In [18]:
my1dArray.dtype

dtype('int64')

In [22]:
## numpy initialisation
number_rows = 2
number_columns = 3

## create arrays of 0 specifying the dataype
array0s = np.zeros((number_rows, number_columns), dtype = np.int16)
print(array0s)

[[0 0 0]
 [0 0 0]]


In [23]:
## create arrays of 1
array1s = np.ones((number_rows, number_columns), dtype = 'float')
print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
